services:
  mongo:
    image: mongo:7
    container_name: mern_mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mern_network

  mongo-express:
    image: mongo-express:latest
    container_name: mern_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT}
    depends_on:
      - mongo
    networks:
      - mern_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    # image: ${ECR_REGISTRY}/my-app:server // use this for ECR deployment , it is already pushed to ECR and it is a private image
    container_name: mern_server
    restart: unless-stopped
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - mern_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    # image: ${ECR_REGISTRY}/my-app:client // use this for ECR deployment , it is already pushed to ECR and it is a private image
    container_name: mern_client
    restart: unless-stopped
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - server
    networks:
      - mern_network

volumes:
  mongo_data:

networks:
  mern_network:
    driver: bridge
